// app/shop/products.ts

// Category type for better type narrowing
export type ProductCategory = 
  | 'Engine Parts' 
  | 'Brake Systems' 
  | 'Tires & Wheels' 
  | 'Electrical' 
  | 'Filters' 
  | 'Body Parts';

export type ProductVariant = {
  size: string;       // e.g., "350ml", "500ml", "1L", "400g", "800g", "per piece"
  price: number;
  unit?: string;      // optional override (e.g., "per bottle" if size already implies unit)
};

export type Product = {
  id: string;
  name: string;
  slug: string;
  category: ProductCategory;
  subcategory?: string;     // Optional subcategory for filtering
  image?: string;           // Cloudinary URL or local path
  isStatic?: boolean;       // true for items from this static file
  // Either price+unit for simple products, or variants for multi-size products
  price?: number;
  unit?: string;
  variants?: ProductVariant[];
  description?: string;     // Optional custom description for products with multiple ingredients
  createdAt?: any;
  updatedAt?: any;
};

export const products: Product[] = [
  // ==================== ENGINE PARTS ====================
  { id: "ep1", name: "Oil Filter", slug: "oil-filter", category: "Filters", subcategory: "Oil Filters", price: 450, unit: "per piece", image: "/images/products/oil-filter.jpg", description: "High-quality oil filter designed to keep your engine oil clean and free from contaminants. Ensures optimal engine performance and longevity." },
  { id: "ep2", name: "Air Filter", slug: "air-filter", category: "Filters", subcategory: "Air Filters", price: 850, unit: "per piece", image: "/images/products/air-filter.jpg", description: "Premium air filter that provides superior air filtration for your engine. Improves fuel efficiency and protects against dust and debris." },
  { id: "ep3", name: "Fuel Filter", slug: "fuel-filter", category: "Filters", subcategory: "Fuel Filters", price: 650, unit: "per piece", image: "/images/products/fuel-filter.jpg", description: "Reliable fuel filter that removes impurities from fuel before it reaches the engine. Essential for maintaining smooth engine operation." },
  { id: "ep4", name: "Spark Plug", slug: "spark-plug", category: "Engine Parts", subcategory: "Engine Components", price: 350, unit: "per piece", image: "/images/products/spark-plug.jpg", description: "Durable spark plug designed for reliable ignition and optimal combustion. Ensures smooth engine starts and consistent performance." },
  { id: "ep5", name: "Timing Belt", slug: "timing-belt", category: "Engine Parts", subcategory: "Timing Parts", price: 2500, unit: "per piece", image: "/images/products/timing-belt.jpg", description: "Precision-engineered timing belt that synchronizes engine camshaft and crankshaft. Critical for maintaining engine timing and preventing damage." },
  { id: "ep6", name: "Alternator", slug: "alternator", category: "Electrical", subcategory: "Alternators", price: 8500, unit: "per piece", image: "/images/products/alternator.jpg", description: "High-output alternator that charges your battery and powers electrical systems. Reliable performance for all driving conditions." },
  { id: "ep7", name: "Starter Motor", slug: "starter-motor", category: "Engine Parts", subcategory: "Engine Components", price: 6500, unit: "per piece", image: "/images/products/starter-motor.jpg", description: "Powerful starter motor that ensures quick and reliable engine cranking. Built to withstand frequent use and harsh conditions." },
  { id: "ep8", name: "Water Pump", slug: "water-pump", category: "Engine Parts", subcategory: "Engine Components", price: 3500, unit: "per piece", image: "/images/products/water-pump.jpg", description: "Efficient water pump that circulates coolant through the engine. Essential for maintaining optimal engine temperature and preventing overheating." },
  { id: "ep9", name: "Thermostat", slug: "thermostat", category: "Engine Parts", subcategory: "Engine Components", price: 1200, unit: "per piece", image: "/images/products/thermostat.jpg", description: "Precision thermostat that regulates engine coolant flow. Helps maintain ideal operating temperature for improved fuel efficiency and engine life." },
  { id: "ep10", name: "Radiator", slug: "radiator", category: "Engine Parts", subcategory: "Engine Components", price: 12000, unit: "per piece", image: "/images/products/radiator.jpg", description: "Durable aluminum radiator that efficiently dissipates heat from the engine coolant. Designed for maximum cooling performance and durability." },
  { id: "of1", name: "Engine Oil 5W-30 (5L)", slug: "engine-oil-5w30-5l", category: "Engine Parts", subcategory: "Engine Components", price: 3500, unit: "per 5L", image: "/images/products/engine-oil-5w30.jpg", description: "Premium synthetic engine oil 5W-30 formulated for superior engine protection. Provides excellent wear protection and maintains viscosity across temperature ranges." },
  { id: "of2", name: "Engine Oil 10W-40 (5L)", slug: "engine-oil-10w40-5l", category: "Engine Parts", subcategory: "Engine Components", price: 3200, unit: "per 5L", image: "/images/products/engine-oil-10w40.jpg", description: "High-quality mineral engine oil 10W-40 suitable for a wide range of vehicles. Offers reliable protection and extended drain intervals." },
  { id: "of3", name: "Gear Oil 80W-90 (1L)", slug: "gear-oil-80w90-1l", category: "Engine Parts", subcategory: "Engine Components", price: 650, unit: "per liter", image: "/images/products/gear-oil.jpg", description: "Heavy-duty gear oil 80W-90 designed for manual transmissions and differentials. Provides excellent extreme pressure protection and smooth shifting." },
  { id: "of4", name: "Transmission Fluid (1L)", slug: "transmission-fluid-1l", category: "Engine Parts", subcategory: "Engine Components", price: 850, unit: "per liter", image: "/images/products/transmission-fluid.jpg", description: "Premium automatic transmission fluid that ensures smooth gear shifts and optimal transmission performance. Protects against wear and overheating." },
  { id: "of5", name: "Coolant (5L)", slug: "coolant-5l", category: "Engine Parts", subcategory: "Engine Components", price: 1800, unit: "per 5L", image: "/images/products/coolant.jpg", description: "Long-life antifreeze coolant that protects the engine from freezing and overheating. Contains corrosion inhibitors for extended cooling system life." },
  { id: "of6", name: "Power Steering Fluid (1L)", slug: "power-steering-fluid-1l", category: "Engine Parts", subcategory: "Engine Components", price: 550, unit: "per liter", image: "/images/products/power-steering-fluid.jpg", description: "High-performance power steering fluid that ensures smooth and responsive steering. Protects seals and hoses from wear and degradation." },
  { id: "of7", name: "Windshield Washer Fluid (1L)", slug: "windshield-washer-fluid-1l", category: "Engine Parts", subcategory: "Engine Components", price: 250, unit: "per liter", image: "/images/products/washer-fluid.jpg", description: "Effective windshield washer fluid that removes dirt, bugs, and grime for clear visibility. Safe for all vehicle paint and rubber surfaces." },
  { id: "of8", name: "Brake Fluid DOT4 (500ml)", slug: "brake-fluid-dot4-500ml", category: "Engine Parts", subcategory: "Engine Components", price: 450, unit: "per 500ml", image: "/images/products/brake-fluid.jpg", description: "High-quality DOT4 brake fluid with excellent boiling point stability. Ensures consistent brake performance and protects brake system components." },

  // ==================== BRAKE SYSTEMS ====================
  { id: "bs1", name: "Brake Pads (Front)", slug: "brake-pads-front", category: "Brake Systems", subcategory: "Brake Pads", price: 2500, unit: "per set", image: "/images/products/brake-pads-front.jpg", description: "Premium front brake pads with excellent friction material for reliable stopping power. Low dust formula keeps wheels cleaner longer." },
  { id: "bs2", name: "Brake Pads (Rear)", slug: "brake-pads-rear", category: "Brake Systems", subcategory: "Brake Pads", price: 1800, unit: "per set", image: "/images/products/brake-pads-rear.jpg", description: "Quality rear brake pads designed for smooth and quiet braking. Provides consistent performance and extended pad life." },
  { id: "bs3", name: "Brake Disc (Front)", slug: "brake-disc-front", category: "Brake Systems", subcategory: "Brake Discs", price: 3500, unit: "per piece", image: "/images/products/brake-disc-front.jpg", description: "Precision-machined front brake disc with excellent heat dissipation. Provides smooth braking and resists warping under heavy use." },
  { id: "bs4", name: "Brake Disc (Rear)", slug: "brake-disc-rear", category: "Brake Systems", subcategory: "Brake Discs", price: 2800, unit: "per piece", image: "/images/products/brake-disc-rear.jpg", description: "Durable rear brake disc with precision ventilation for optimal cooling. Ensures consistent braking performance in all conditions." },
  { id: "bs5", name: "Brake Fluid DOT4", slug: "brake-fluid-dot4", category: "Engine Parts", subcategory: "Engine Components", price: 850, unit: "per liter", image: "/images/products/brake-fluid.jpg", description: "High-quality DOT4 brake fluid with excellent boiling point stability. Ensures consistent brake performance and protects brake system components." },
  { id: "bs6", name: "Brake Caliper", slug: "brake-caliper", category: "Brake Systems", subcategory: "Brake Fluid", price: 4500, unit: "per piece", image: "/images/products/brake-caliper.jpg", description: "OEM-quality brake caliper that applies even pressure to brake pads. Precision-engineered for reliable and responsive braking." },
  { id: "bs7", name: "Brake Hose", slug: "brake-hose", category: "Brake Systems", subcategory: "Brake Fluid", price: 650, unit: "per piece", image: "/images/products/brake-hose.jpg", description: "Durable reinforced brake hose that withstands high pressure and temperature. Ensures consistent brake fluid delivery to the caliper." },
  { id: "bs8", name: "Brake Master Cylinder", slug: "brake-master-cylinder", category: "Brake Systems", subcategory: "Brake Fluid", price: 5500, unit: "per piece", image: "/images/products/brake-master-cylinder.jpg", description: "Reliable brake master cylinder that converts pedal pressure into hydraulic force. Essential for proper brake system operation and safety." },

  // ==================== TIRES & WHEELS ====================
  { id: "tw1", name: "Tire 185/65R15", slug: "tire-185-65r15", category: "Tires & Wheels", subcategory: "Tires", price: 6500, unit: "per piece", image: "/images/products/tire-185.jpg", description: "All-season passenger tire 185/65R15 with excellent wet and dry grip. Provides a smooth, quiet ride with long tread life." },
  { id: "tw2", name: "Tire 195/65R15", slug: "tire-195-65r15", category: "Tires & Wheels", subcategory: "Tires", price: 7500, unit: "per piece", image: "/images/products/tire-195.jpg", description: "Versatile all-season tire 195/65R15 offering balanced performance for daily driving. Excellent traction and fuel efficiency." },
  { id: "tw3", name: "Tire 205/55R16", slug: "tire-205-55r16", category: "Tires & Wheels", subcategory: "Tires", price: 9500, unit: "per piece", image: "/images/products/tire-205.jpg", description: "Performance-oriented tire 205/55R16 with superior handling and stability. Ideal for sporty driving with excellent wet weather performance." },
  { id: "tw4", name: "Alloy Wheel 15 inch", slug: "alloy-wheel-15", category: "Tires & Wheels", subcategory: "Rims", price: 8500, unit: "per piece", image: "/images/products/alloy-wheel-15.jpg", description: "Lightweight 15-inch alloy wheel with a stylish design. Improves handling and reduces unsprung weight for better performance." },
  { id: "tw5", name: "Alloy Wheel 16 inch", slug: "alloy-wheel-16", category: "Tires & Wheels", subcategory: "Rims", price: 12000, unit: "per piece", image: "/images/products/alloy-wheel-16.jpg", description: "Premium 16-inch alloy wheel with a durable finish. Enhances vehicle appearance while providing superior strength and corrosion resistance." },
  { id: "tw6", name: "Steel Wheel 15 inch", slug: "steel-wheel-15", category: "Tires & Wheels", subcategory: "Rims", price: 3500, unit: "per piece", image: "/images/products/steel-wheel-15.jpg", description: "Durable 15-inch steel wheel built for strength and reliability. Perfect for everyday driving and fleet vehicles." },
  { id: "tw7", name: "Wheel Hub", slug: "wheel-hub", category: "Tires & Wheels", subcategory: "Rims", price: 2500, unit: "per piece", image: "/images/products/wheel-hub.jpg", description: "Precision-engineered wheel hub that ensures smooth wheel rotation. Built to withstand heavy loads and provide long service life." },
  { id: "tw8", name: "Lug Nut Set", slug: "lug-nut-set", category: "Tires & Wheels", subcategory: "Valve Caps", price: 850, unit: "per set", image: "/images/products/lug-nut.jpg", description: "Complete set of high-quality lug nuts for secure wheel mounting. Corrosion-resistant finish ensures easy removal and long-lasting performance." },
  { id: "tw9", name: "Tire Pressure Gauge", slug: "tire-pressure-gauge", category: "Tires & Wheels", subcategory: "Tires", price: 650, unit: "per piece", image: "/images/products/tire-gauge.jpg", description: "Accurate digital tire pressure gauge for maintaining optimal tire pressure. Helps improve fuel efficiency and extend tire life." },

  // ==================== ELECTRICAL ====================
  { id: "el1", name: "Car Battery 12V", slug: "car-battery-12v", category: "Electrical", subcategory: "Batteries", price: 8500, unit: "per piece", image: "/images/products/car-battery.jpg", description: "High-capacity 12V car battery with excellent cold cranking power. Maintenance-free design with long service life for reliable starts." },
  { id: "el2", name: "Headlight Bulb (H7)", slug: "headlight-bulb-h7", category: "Electrical", subcategory: "Lighting", price: 450, unit: "per piece", image: "/images/products/headlight-bulb.jpg", description: "Bright H7 headlight bulb with excellent visibility and long lifespan. Provides crisp white light for safer night driving." },
  { id: "el3", name: "Tail Light Assembly", slug: "tail-light-assembly", category: "Electrical", subcategory: "Lighting", price: 3500, unit: "per piece", image: "/images/products/tail-light.jpg", description: "Complete tail light assembly with all bulbs and reflectors. DOT-approved design ensures visibility and safety on the road." },
  { id: "el4", name: "Wiper Blade (22 inch)", slug: "wiper-blade-22", category: "Electrical", subcategory: "Lighting", price: 650, unit: "per piece", image: "/images/products/wiper-blade.jpg", description: "Premium 22-inch wiper blade with natural rubber for streak-free wiping. All-weather design for clear visibility in rain and snow." },
  { id: "el5", name: "Wiper Motor", slug: "wiper-motor", category: "Electrical", subcategory: "Lighting", price: 4500, unit: "per piece", image: "/images/products/wiper-motor.jpg", description: "Powerful wiper motor that operates smoothly at all speeds. Durable construction for reliable performance in all weather conditions." },
  { id: "el6", name: "Ignition Coil", slug: "ignition-coil", category: "Electrical", subcategory: "Starters", price: 2500, unit: "per piece", image: "/images/products/ignition-coil.jpg", description: "High-performance ignition coil that delivers strong spark for efficient combustion. Improves engine performance and fuel economy." },
  { id: "el7", name: "Fuse Box", slug: "fuse-box", category: "Electrical", subcategory: "Lighting", price: 1800, unit: "per piece", image: "/images/products/fuse-box.jpg", description: "Complete fuse box assembly with all necessary fuses and relays. Protects electrical circuits from overload and short circuits." },
  { id: "el8", name: "Relay Switch", slug: "relay-switch", category: "Electrical", subcategory: "Lighting", price: 350, unit: "per piece", image: "/images/products/relay-switch.jpg", description: "Heavy-duty relay switch for controlling high-current electrical circuits. Provides reliable switching for lights, fans, and other accessories." },
  { id: "el9", name: "Horn", slug: "horn", category: "Electrical", subcategory: "Lighting", price: 850, unit: "per piece", image: "/images/products/horn.jpg", description: "Loud and clear electric horn that meets safety standards. Durable construction for reliable operation in all conditions." },
  { id: "el10", name: "Voltage Regulator", slug: "voltage-regulator", category: "Electrical", subcategory: "Lighting", price: 1200, unit: "per piece", image: "/images/products/voltage-regulator.jpg", description: "Precision voltage regulator that maintains stable electrical system voltage. Protects sensitive electronics from voltage spikes and surges." },

  // ==================== FILTERS ====================
  { id: "fl1", name: "Cabin Air Filter", slug: "cabin-air-filter", category: "Filters", subcategory: "Air Filters", price: 1200, unit: "per piece", image: "/images/products/cabin-air-filter.jpg", description: "High-efficiency cabin air filter that removes dust, pollen, and odors from the air. Ensures clean and fresh air inside the vehicle." },
  { id: "fl2", name: "Transmission Filter", slug: "transmission-filter", category: "Filters", subcategory: "Oil Filters", price: 1800, unit: "per piece", image: "/images/products/transmission-filter.jpg", description: "Premium transmission filter that removes contaminants from transmission fluid. Essential for smooth shifting and extended transmission life." },
  { id: "fl3", name: "Fuel Filter (Inline)", slug: "fuel-filter-inline", category: "Filters", subcategory: "Fuel Filters", price: 950, unit: "per piece", image: "/images/products/fuel-filter-inline.jpg", description: "Inline fuel filter that traps water and particles from fuel. Protects fuel injectors and ensures clean combustion." },
  { id: "fl4", name: "PCV Valve", slug: "pcv-valve", category: "Filters", subcategory: "Air Filters", price: 450, unit: "per piece", image: "/images/products/pcv-valve.jpg", description: "Positive crankcase ventilation valve that reduces emissions and prevents sludge buildup. Improves engine efficiency and reduces oil leaks." },

  // ==================== BODY PARTS ====================
  { id: "bp1", name: "Front Bumper", slug: "front-bumper", category: "Body Parts", subcategory: "Bumpers", price: 8500, unit: "per piece", image: "/images/products/front-bumper.jpg", description: "OEM-style front bumper with perfect fit and finish. Made from durable polypropylene to absorb impact and protect vital components." },
  { id: "bp2", name: "Rear Bumper", slug: "rear-bumper", category: "Body Parts", subcategory: "Bumpers", price: 7500, unit: "per piece", image: "/images/products/rear-bumper.jpg", description: "High-quality rear bumper with integrated mounting points. Provides excellent protection and matches your vehicle's original styling." },
  { id: "bp3", name: "Hood", slug: "hood", category: "Body Parts", price: 15000, unit: "per piece", image: "/images/products/hood.jpg", description: "Precision-formed hood panel with proper alignment and fit. Made from high-grade steel for durability and corrosion resistance." },
  { id: "bp4", name: "Fender (Front Left)", slug: "fender-front-left", category: "Body Parts", subcategory: "Fenders", price: 5500, unit: "per piece", image: "/images/products/fender-front.jpg", description: "Front left fender with exact factory specifications. Protects the wheel arch and enhances vehicle appearance." },
  { id: "bp5", name: "Fender (Front Right)", slug: "fender-front-right", category: "Body Parts", subcategory: "Fenders", price: 5500, unit: "per piece", image: "/images/products/fender-front.jpg", description: "Front right fender with exact factory specifications. Protects the wheel arch and enhances vehicle appearance." },
  { id: "bp6", name: "Door Panel (Front)", slug: "door-panel-front", category: "Body Parts", price: 6500, unit: "per piece", image: "/images/products/door-panel.jpg", description: "Front door panel with proper fit and finish. Includes mounting points for interior trim and handles." },
  { id: "bp7", name: "Side Mirror (Left)", slug: "side-mirror-left", category: "Body Parts", subcategory: "Mirrors", price: 2500, unit: "per piece", image: "/images/products/side-mirror.jpg", description: "Left side mirror with integrated turn signal. Provides excellent visibility and matches your vehicle's styling." },
  { id: "bp8", name: "Side Mirror (Right)", slug: "side-mirror-right", category: "Body Parts", subcategory: "Mirrors", price: 2500, unit: "per piece", image: "/images/products/side-mirror.jpg", description: "Right side mirror with integrated turn signal. Provides excellent visibility and matches your vehicle's styling." },
  { id: "bp9", name: "Windshield", slug: "windshield", category: "Body Parts", subcategory: "Lights", price: 12000, unit: "per piece", image: "/images/products/windshield.jpg", description: "Laminated safety windshield with UV protection. Provides clear visibility and structural integrity for passenger safety." },
  { id: "bp10", name: "Rear Window", slug: "rear-window", category: "Body Parts", subcategory: "Lights", price: 8500, unit: "per piece", image: "/images/products/rear-window.jpg", description: "Tempered glass rear window with defroster grid. Provides rear visibility and structural support for the vehicle." },
  { id: "ss1", name: "Shock Absorber (Front)", slug: "shock-absorber-front", category: "Body Parts", price: 3500, unit: "per piece", image: "/images/products/shock-absorber-front.jpg", description: "Front shock absorber that controls spring movement for a smooth ride. Reduces body roll and improves handling and stability." },
  { id: "ss2", name: "Shock Absorber (Rear)", slug: "shock-absorber-rear", category: "Body Parts", price: 2800, unit: "per piece", image: "/images/products/shock-absorber-rear.jpg", description: "Rear shock absorber that ensures comfortable and controlled rides. Durable construction for long service life." },
  { id: "ss3", name: "Strut Assembly", slug: "strut-assembly", category: "Body Parts", price: 8500, unit: "per piece", image: "/images/products/strut-assembly.jpg", description: "Complete strut assembly with coil spring and mount. Provides structural support and suspension damping for optimal ride quality." },
  { id: "ss4", name: "Control Arm", slug: "control-arm", category: "Body Parts", price: 4500, unit: "per piece", image: "/images/products/control-arm.jpg", description: "Heavy-duty control arm that connects the wheel to the vehicle frame. Ensures precise wheel alignment and handling." },
  { id: "ss5", name: "Ball Joint", slug: "ball-joint", category: "Body Parts", price: 1800, unit: "per piece", image: "/images/products/ball-joint.jpg", description: "Durable ball joint that allows smooth suspension movement. Essential for steering precision and ride comfort." },
  { id: "ss6", name: "Tie Rod End", slug: "tie-rod-end", category: "Body Parts", price: 1500, unit: "per piece", image: "/images/products/tie-rod-end.jpg", description: "Precision tie rod end that connects the steering rack to the wheel. Ensures accurate steering response and alignment." },
  { id: "ss7", name: "Wheel Bearing", slug: "wheel-bearing", category: "Body Parts", price: 2200, unit: "per piece", image: "/images/products/wheel-bearing.jpg", description: "Sealed wheel bearing that allows smooth wheel rotation. Reduces friction and prevents premature tire wear." },
  { id: "ss8", name: "Steering Rack", slug: "steering-rack", category: "Body Parts", price: 15000, unit: "per piece", image: "/images/products/steering-rack.jpg", description: "Complete steering rack with inner and outer tie rods. Provides precise steering control and responsive handling." },
  { id: "ac1", name: "Car Cover (Medium)", slug: "car-cover-medium", category: "Body Parts", price: 3500, unit: "per piece", image: "/images/products/car-cover.jpg", description: "Waterproof car cover for medium-sized vehicles. Protects against dust, UV rays, and light rain with breathable fabric." },
  { id: "ac2", name: "Car Cover (Large)", slug: "car-cover-large", category: "Body Parts", price: 4500, unit: "per piece", image: "/images/products/car-cover.jpg", description: "Heavy-duty car cover for large vehicles and SUVs. All-weather protection with reinforced seams and elastic hems." },
  { id: "ac3", name: "Seat Cover Set", slug: "seat-cover-set", category: "Body Parts", price: 2500, unit: "per set", image: "/images/products/seat-cover.jpg", description: "Universal fit seat cover set that protects your seats from wear and spills. Easy to install and machine washable." },
  { id: "ac4", name: "Floor Mat Set", slug: "floor-mat-set", category: "Body Parts", price: 1800, unit: "per set", image: "/images/products/floor-mat.jpg", description: "Durable all-weather floor mat set that traps dirt and moisture. Custom fit design for maximum protection of your vehicle's interior." },
  { id: "ac5", name: "Steering Wheel Cover", slug: "steering-wheel-cover", category: "Body Parts", price: 650, unit: "per piece", image: "/images/products/steering-cover.jpg", description: "Comfortable steering wheel cover with anti-slip grip. Improves driving comfort and protects your steering wheel from wear." },
  { id: "ac6", name: "Phone Mount", slug: "phone-mount", category: "Body Parts", price: 850, unit: "per piece", image: "/images/products/phone-mount.jpg", description: "Adjustable phone mount that securely holds your device for navigation. 360-degree rotation for optimal viewing angle." },
  { id: "ac7", name: "Dash Cam", slug: "dash-cam", category: "Body Parts", price: 5500, unit: "per piece", image: "/images/products/dash-cam.jpg", description: "HD dash camera that records your drives for safety and security. Features night vision and loop recording." },
  { id: "ac8", name: "Car Vacuum Cleaner", slug: "car-vacuum", category: "Body Parts", price: 3500, unit: "per piece", image: "/images/products/car-vacuum.jpg", description: "Portable car vacuum cleaner with strong suction. Includes multiple attachments for cleaning seats, carpets, and hard-to-reach areas." },
  { id: "ac9", name: "Jump Starter", slug: "jump-starter", category: "Body Parts", price: 8500, unit: "per piece", image: "/images/products/jump-starter.jpg", description: "Portable jump starter pack that provides instant power for dead batteries. Compact design with built-in safety features." },
  { id: "ac10", name: "Tow Hook", slug: "tow-hook", category: "Body Parts", price: 1200, unit: "per piece", image: "/images/products/tow-hook.jpg", description: "Heavy-duty tow hook for emergency vehicle recovery. Rated for maximum towing capacity with secure mounting." },
  { id: "o1", name: "Jumper Cables", slug: "jumper-cables", category: "Body Parts", price: 1500, unit: "per set", image: "/images/products/jumper-cables.jpg", description: "Heavy-gauge jumper cables for jump-starting dead batteries. Includes safety gloves and instructions for safe use." },
  { id: "o2", name: "Tool Kit (Basic)", slug: "tool-kit-basic", category: "Body Parts", price: 3500, unit: "per set", image: "/images/products/tool-kit.jpg", description: "Comprehensive basic tool kit with essential wrenches, screwdrivers, and pliers. Perfect for everyday repairs and maintenance." },
  { id: "o3", name: "Jack (2 Ton)", slug: "jack-2-ton", category: "Body Parts", price: 4500, unit: "per piece", image: "/images/products/jack.jpg", description: "Heavy-duty 2-ton hydraulic jack for safe vehicle lifting. Features a wide base for stability and easy operation." },
  { id: "o4", name: "Jack Stand (Pair)", slug: "jack-stand-pair", category: "Body Parts", price: 2500, unit: "per pair", image: "/images/products/jack-stand.jpg", description: "Pair of heavy-duty jack stands for secure vehicle support. Adjustable height with locking pins for safety." },
  { id: "o5", name: "Wrench Set (Metric)", slug: "wrench-set-metric", category: "Body Parts", price: 2800, unit: "per set", image: "/images/products/wrench-set.jpg", description: "Complete metric wrench set with combination and open-end wrenches. Chrome vanadium steel for durability and corrosion resistance." },
  { id: "o6", name: "Socket Set", slug: "socket-set", category: "Body Parts", price: 3500, unit: "per set", image: "/images/products/socket-set.jpg", description: "Comprehensive socket set with ratchet handle and extensions. Includes both metric and standard sockets for all applications." },
  { id: "o7", name: "Screwdriver Set", slug: "screwdriver-set", category: "Body Parts", price: 1200, unit: "per set", image: "/images/products/screwdriver-set.jpg", description: "Professional screwdriver set with Phillips and flathead tips. Ergonomic handles for comfortable grip and torque." },
  { id: "o8", name: "Pliers Set", slug: "pliers-set", category: "Body Parts", price: 1500, unit: "per set", image: "/images/products/pliers-set.jpg", description: "Versatile pliers set including needle-nose, slip-joint, and cutting pliers. Drop-forged steel for strength and durability." },
];
